name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install -r docs/requirements.txt
        name: Install mkdocs dependencies

      - run: |
          git config --local user.name ci-bot
          git config --local user.email ci-bot@example.com
        name: Setting up git for deployer
      - run: python -m mkdocs gh-deploy -b gh-pages --force
        name: Build docs